api_platform:
    title: 'Seaswim API'
    version: '1.0.0'
    defaults:
        stateless: true
        cache_headers:
            max_age: 300
            shared_max_age: 600
    formats:
        json:
            mime_types: ['application/json']
    docs_formats:
        json: true
        jsonld: false
        html: true
